# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0003_auto_20171217_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('authors', models.CharField(max_length=512)),
                ('journal', models.CharField(max_length=128)),
                ('pubmed_link', models.CharField(max_length=128)),
                ('doi_link', models.CharField(max_length=128)),
            ],
        ),
    ]
