# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0004_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.CharField(default='2012', max_length=32),
        ),
    ]
