# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0005_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.CharField(default='Empty', max_length=2048),
        ),
    ]
