# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0006_publication_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=1024),
        ),
    ]
