# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0007_auto_20171218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.CharField(default='Empty', max_length=10000),
        ),
    ]
