# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0008_auto_20171218_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=15000)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=15000)),
            ],
        ),
    ]
