# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0009_feedbackfaq_simplefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplefeedback',
            name='author',
            field=models.CharField(default='Anonymous', max_length=128),
        ),
    ]
