# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0010_simplefeedback_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackfaq',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='simplefeedback',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='feedbackfaq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simplefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
