# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0012_news'),
    ]

    operations = [
    ]
