# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 23:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fbb_site', '0013_auto_20180104_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
